# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - test -d node_modules
  build:
    commands:
      - echo Build started
      - echo Compiling the Node.js code
      - npm run build
      - echo Testing if files exist
      - test -f server.js
      - test -f dist/index.html
      - test -f dist/main.js
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - server.js
    - dist/*
    - package.json
    - node_modules/*
